echo "Cleaning previous builds first.."
rm -rf dist
rm -rf build
rm -rf thompson.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf .pylint.d
rm -rf thompson/data/*.zip
rm -rf thompson/data/*.bif
rm -rf thompson/data/*.png
rm -rf thompson/data/*.txt
rm -rf thompson/data/*.json
rm -rf thompson/data/*.csv
rm -rf thompson/__pycache__
rm -rf thompson/helpers/__pycache__
rm -rf thompson/tests/__pycache__
rm -rf thompson/thompson/*.pkl
rm -rf thompson/thompson/*.html
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf *.pkl
